/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as SigninIndexRouteImport } from './routes/signin/index'
import { Route as PricingIndexRouteImport } from './routes/pricing/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ExpInfiniRouteImport } from './routes/exp/infini'
import { Route as ChatCanvasIdRouteImport } from './routes/chat/$canvasId'
import { Route as AccountYour_keysIndexRouteImport } from './routes/account/your_keys/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninIndexRoute = SigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpInfiniRoute = ExpInfiniRouteImport.update({
  id: '/exp/infini',
  path: '/exp/infini',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatCanvasIdRoute = ChatCanvasIdRouteImport.update({
  id: '/chat/$canvasId',
  path: '/chat/$canvasId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountYour_keysIndexRoute = AccountYour_keysIndexRouteImport.update({
  id: '/account/your_keys/',
  path: '/account/your_keys/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat/$canvasId': typeof ChatCanvasIdRoute
  '/exp/infini': typeof ExpInfiniRoute
  '/chat': typeof ChatIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/signin': typeof SigninIndexRoute
  '/signup': typeof SignupIndexRoute
  '/account/your_keys': typeof AccountYour_keysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat/$canvasId': typeof ChatCanvasIdRoute
  '/exp/infini': typeof ExpInfiniRoute
  '/chat': typeof ChatIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/signin': typeof SigninIndexRoute
  '/signup': typeof SignupIndexRoute
  '/account/your_keys': typeof AccountYour_keysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat/$canvasId': typeof ChatCanvasIdRoute
  '/exp/infini': typeof ExpInfiniRoute
  '/chat/': typeof ChatIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/account/your_keys/': typeof AccountYour_keysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chat/$canvasId'
    | '/exp/infini'
    | '/chat'
    | '/pricing'
    | '/signin'
    | '/signup'
    | '/account/your_keys'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chat/$canvasId'
    | '/exp/infini'
    | '/chat'
    | '/pricing'
    | '/signin'
    | '/signup'
    | '/account/your_keys'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chat/$canvasId'
    | '/exp/infini'
    | '/chat/'
    | '/pricing/'
    | '/signin/'
    | '/signup/'
    | '/account/your_keys/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChatCanvasIdRoute: typeof ChatCanvasIdRoute
  ExpInfiniRoute: typeof ExpInfiniRoute
  ChatIndexRoute: typeof ChatIndexRoute
  PricingIndexRoute: typeof PricingIndexRoute
  SigninIndexRoute: typeof SigninIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  AccountYour_keysIndexRoute: typeof AccountYour_keysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exp/infini': {
      id: '/exp/infini'
      path: '/exp/infini'
      fullPath: '/exp/infini'
      preLoaderRoute: typeof ExpInfiniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$canvasId': {
      id: '/chat/$canvasId'
      path: '/chat/$canvasId'
      fullPath: '/chat/$canvasId'
      preLoaderRoute: typeof ChatCanvasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/your_keys/': {
      id: '/account/your_keys/'
      path: '/account/your_keys'
      fullPath: '/account/your_keys'
      preLoaderRoute: typeof AccountYour_keysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChatCanvasIdRoute: ChatCanvasIdRoute,
  ExpInfiniRoute: ExpInfiniRoute,
  ChatIndexRoute: ChatIndexRoute,
  PricingIndexRoute: PricingIndexRoute,
  SigninIndexRoute: SigninIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  AccountYour_keysIndexRoute: AccountYour_keysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
